# Generated by Django 3.2.7 on 2021-09-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('company', models.CharField(max_length=70)),
                ('title', models.CharField(max_length=70)),
                ('sideBusiness', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('country', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
            ],
        ),
    ]
